### ISSUE TITLE
Enable logging on cloudfront distributions

### ISSUE THREAD

**Issue by ziegeer** [mozilla-it/sumo-infra#28]
Enable logging on cloudfront distributions so that we can diagnose e.g. high 4xx errors.

**Comment by kfferrando** [comment]
Pushed this in d7808c0bf7217e2ec3788b45b97ef899de475739. I am working on correctly creating the S3 bucket with Terraform and applyin ga lifecycle.

There are some interesting bits for CF log processing here:
https://aws.amazon.com/blogs/big-data/build-a-serverless-architecture-to-analyze-amazon-cloudfront-access-logs-using-aws-lambda-amazon-athena-and-amazon-kinesis-analytics/

I will leave this open until all the S3 bucket Terraform has been committed.

**Comment by kfferrando** [comment]
Ok this is live in cca6795f1d7dc914648cd3c31de5e3a03eb2c54e and added 2 week lifecycle on logs in 6404946bf53d03306f9c854d23bb3a4c34a9817d
