### ISSUE TITLE
Create NR synthetics check for search results

### ISSUE THREAD

**Issue by ziegeer** [mozilla-it/sumo-infra#30]
We had an outage of search results because of a bad library upgrade and didn't get an alert because the increased error rate was not large enough to trigger alerts.  A check specific to search results that maybe alerts slack only would be a good addition.

**Comment by kfferrando** [comment]
This has been setup and in place for a while.

https://synthetics.newrelic.com/accounts/2239138/monitors/ea6bab9e-f423-4012-b292-9c8dd04e1df0
